@startuml
class com.engine.Camera {
- Vector2D position
+ <<Create>> Camera(Vector2D)
+ Vector2D getPosition()
+ void setPosition(Vector2D)
}
abstract class com.engine.Component {
- GameObject gameObject
+ void update(double)
+ void draw(Graphics2D)
+ {abstract}Component copy()
+ void start()
+ GameObject getGameObject()
+ void setGameObject(GameObject)
}
class com.util.AssetPool {
- {static} Map<String,Sprite> sprites
- <<Create>> AssetPool()
+ {static} boolean hasSprite(String)
+ {static} Sprite getSprite(String)
+ {static} void addSprite(String,Sprite)
}
class com.util.Vector2D {
- double x
- double y
+ <<Create>> Vector2D(double,double)
+ <<Create>> Vector2D()
+ Vector2D copy()
+ double getX()
+ void setX(double)
+ double getY()
+ void setY(double)
}
abstract class com.engine.Scene {
- String name
- Camera camera
- List<GameObject> gameObjects
- Renderer renderer
# <<Create>> Scene(String)
+ void addGameObject(GameObject)
+ {abstract}void init()
+ {abstract}void update(double)
+ {abstract}void draw(Graphics2D)
+ String getName()
+ void setName(String)
+ Camera getCamera()
+ void setCamera(Camera)
+ List<GameObject> getGameObjects()
+ void setGameObjects(List<GameObject>)
+ Renderer getRenderer()
+ void setRenderer(Renderer)
}
class com.util.Constants {
+ {static} int SCREEN_WIDTH
+ {static} int SCREEN_HEIGHT
+ {static} String SCREEN_TITLE
+ {static} int PLAYER_HEIGHT
+ {static} int PLAYER_WIDTH
+ {static} int GROUND_Y
+ {static} int CAMERA_OFFSET_X
+ {static} int CAMERA_OFFSET_Y
+ {static} int CAMERA_OFFSET_GROUND_Y
+ {static} double GRAVITY
+ {static} double TERMINAL_VELOCITY
+ {static} int TILE_HEIGHT
+ {static} int TILE_WIDTH
+ {static} int BUTTON_OFFSET_X
+ {static} int BUTTON_OFFSET_Y
+ {static} int BUTTON_SPACING_HZ
+ {static} int BUTTON_SPACING_VT
+ {static} int BUTTON_HEIGHT
+ {static} int BUTTON_WIDTH
- <<Create>> Constants()
}
class com.engine.LevelEditorScene {
- GameObject player
- GameObject ground
- Grid grid
- CameraControls cameraControls
- GameObject cursor
- MainContainer editingButtons
+ <<Create>> LevelEditorScene(String)
+ void init()
+ void update(double)
+ void draw(Graphics2D)
+ GameObject getPlayer()
+ void setPlayer(GameObject)
+ GameObject getCursor()
+ void setCursor(GameObject)
}
class com.components.RigidBody {
- Vector2D velocity
+ <<Create>> RigidBody(Vector2D)
+ void update(double)
+ Component copy()
+ Vector2D getVelocity()
+ void setVelocity(Vector2D)
}
class com.engine.KeyListener {
- boolean[] keyPressed
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
+ boolean isKeyPressed(int)
}
class com.components.CameraControls {
- double prevMx
- double prevMy
+ <<Create>> CameraControls()
+ void update(double)
+ CameraControls copy()
}
class com.util.Time {
- {static} double timeStarted
- <<Create>> Time()
+ {static} double getTime()
+ {static} double getTimeStarted()
+ {static} void setTimeStarted(double)
}
class com.engine.LevelScene {
- GameObject player
+ <<Create>> LevelScene(String)
+ void init()
+ void update(double)
+ void draw(Graphics2D)
+ GameObject getPlayer()
+ void setPlayer(GameObject)
}
class com.components.Grid {
~ Camera camera
- int width
- int height
- int numYLines
- int numXLines
+ <<Create>> Grid()
+ void update(double)
+ void draw(Graphics2D)
+ Component copy()
+ int getWidth()
+ void setWidth(int)
+ int getHeight()
+ void setHeight(int)
}
class com.main.Main {
+ {static} void main(String[])
}
class com.ui.MainContainer {
- List<GameObject> menuItems
+ <<Create>> MainContainer()
+ void init()
+ void start()
+ void update(double)
+ Component copy()
+ void draw(Graphics2D)
}
class com.components.Spritesheet {
- List<Sprite> sprites
- int tileWidth
- int tileHeight
- int spacing
+ <<Create>> Spritesheet(String,int,int,int,int,int)
+ List<Sprite> getSprites()
+ void setSprites(List<Sprite>)
+ int getTileWidth()
+ void setTileWidth(int)
+ int getTileHeight()
+ void setTileHeight(int)
+ int getSpacing()
+ void setSpacing(int)
}
class com.engine.GameObject {
- List<Component> components
- String name
- Transform transform
+ <<Create>> GameObject(String,Transform)
+ T getComponent(Class<T>)
+ T removeComponent(Class<T>)
+ List<Component> getComponents()
+ void addComponent(Component)
+ GameObject copy()
+ void update(double)
+ void draw(Graphics2D)
+ Transform getTransform()
+ void setTransform(Transform)
}
class com.components.BoxBounds {
- double width
- double height
+ <<Create>> BoxBounds(double,double)
+ void update(double)
+ BoxBounds copy()
+ double getWidth()
+ void setWidth(double)
+ double getHeight()
+ void setHeight(double)
}
class com.components.SnapToGrid {
- double debounceTime
- double debounceLeft
- int width
- int height
+ <<Create>> SnapToGrid(int,int)
+ void update(double)
+ void draw(Graphics2D)
+ Component copy()
+ int getWidth()
+ void setWidth(int)
+ int getHeight()
+ void setHeight(int)
}
class com.engine.Window {
- MouseListener mouseListener
- KeyListener keyListener
- boolean isInEditor
- {static} Window window
- boolean isRunning
- Scene currentScene
- Image doubleBufferImage
- Graphics doubleBufferGraphics
+ <<Create>> Window()
+ void init()
+ Scene getCurrentScene()
+ void changeScene(int)
+ {static} Window getWindow()
+ void update(double)
+ void draw(Graphics)
+ void renderOffscreen(Graphics)
+ void run()
+ MouseListener getMouseListener()
+ void setMouseListener(MouseListener)
+ KeyListener getKeyListener()
+ void setKeyListener(KeyListener)
+ boolean isInEditor()
+ void setInEditor(boolean)
}
class com.components.Sprite {
- String file
- int width
- int height
- BufferedImage image
- boolean isSubsprite
- int row
- int column
- int index
+ <<Create>> Sprite(String)
+ <<Create>> Sprite(BufferedImage)
+ <<Create>> Sprite(BufferedImage,int,int,int)
+ void draw(Graphics2D)
+ Component copy()
+ String getFile()
+ void setFile(String)
+ int getWidth()
+ void setWidth(int)
+ int getHeight()
+ void setHeight(int)
+ BufferedImage getImage()
+ void setImage(BufferedImage)
+ boolean isSubsprite()
+ void setSubsprite(boolean)
+ int getRow()
+ void setRow(int)
+ int getColumn()
+ void setColumn(int)
+ int getIndex()
+ void setIndex(int)
}
class com.engine.MouseListener {
- boolean mousePressed
- boolean mouseDragged
- float x
- float y
- float dx
- float dy
- int mouseButton
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseMoved(MouseEvent)
+ void mouseDragged(MouseEvent)
+ boolean isMousePressed()
+ void setMousePressed(boolean)
+ boolean isMouseDragged()
+ void setMouseDragged(boolean)
+ float getX()
+ void setX(float)
+ float getY()
+ void setY(float)
+ float getDx()
+ void setDx(float)
+ float getDy()
+ void setDy(float)
+ int getMouseButton()
+ void setMouseButton(int)
}
class com.components.Ground {
+ void update(double)
+ void draw(Graphics2D)
+ Component copy()
}
class com.ui.MenuItem {
- int x
- int y
- int width
- int height
- Sprite buttonSprite
- Sprite hoverSprite
- Sprite imageAttached
- boolean isSelected
- int bufferX
- int bufferY
+ <<Create>> MenuItem(int,int,int,int,Sprite,Sprite)
+ void start()
+ void update(double)
+ Component copy()
+ void draw(Graphics2D)
}
class com.components.Player {
- Sprite layerOne
- Sprite layerTwo
- Sprite layerThree
- int width
- int height
+ <<Create>> Player(Sprite,Sprite,Sprite,Color,Color)
+ void draw(Graphics2D)
+ Component copy()
+ Sprite getLayerOne()
+ void setLayerOne(Sprite)
+ Sprite getLayerTwo()
+ void setLayerTwo(Sprite)
+ Sprite getLayerThree()
+ void setLayerThree(Sprite)
+ int getWidth()
+ void setWidth(int)
+ int getHeight()
+ void setHeight(int)
}
class com.engine.Renderer {
- List<GameObject> gameObjects
- Camera camera
+ <<Create>> Renderer(Camera)
+ void submit(GameObject)
+ void render(Graphics2D)
+ List<GameObject> getGameObjects()
+ void setGameObjects(List<GameObject>)
+ Camera getCamera()
+ void setCamera(Camera)
}
class com.util.Transform {
- Vector2D position
- double rotation
- Vector2D scale
+ <<Create>> Transform(Vector2D)
+ Transform copy()
+ String toString()
+ Vector2D getPosition()
+ void setPosition(Vector2D)
+ double getRotation()
+ void setRotation(double)
+ Vector2D getScale()
+ void setScale(Vector2D)
}



'------------------------------------------------
' Inheritance
'------------------------------------------------

com.engine.Scene <|-- com.engine.LevelEditorScene
com.engine.Scene <|-- com.engine.LevelScene

com.engine.KeyListener <|.. com.engine.KeyListener
java.awt.event.KeyAdapter <|-- com.engine.KeyListener

java.awt.event.MouseAdapter <|-- com.engine.MouseListener

com.engine.Component <|-- com.components.CameraControls
com.engine.Component <|-- com.components.RigidBody
com.engine.Component <|-- com.components.Grid
com.engine.Component <|-- com.ui.MainContainer
com.engine.Component <|-- com.components.BoxBounds
com.engine.Component <|-- com.components.SnapToGrid
com.engine.Component <|-- com.components.Sprite
com.engine.Component <|-- com.components.Ground
com.engine.Component <|-- com.ui.MenuItem
com.engine.Component <|-- com.components.Player

com.engine.Runnable <|.. com.engine.Window

javax.swing.JFrame <|-- com.engine.Window

'------------------------------------------------
' Agregation
'------------------------------------------------

com.components.Player o-- com.components.Sprite

com.components.Grid o-- com.engine.Camera

com.components.Ground o-- com.engine.LevelScene
com.components.Ground o-- com.engine.GameObject

com.components.RigidBody o-- com.util.Vector2D

com.components.Sprite o-- java.awt.image.BufferedImage

com.engine.Camera o-- com.util.Vector2D

com.engine.GameObject o-- com.util.Transform

com.ui.MenuItem o-- com.components.Sprite

com.util.Transform o--  com.util.Vector2D

'------------------------------------------------
' Composition
'------------------------------------------------

com.components.Grid *-- java.awt.geom.AffineTransform

com.components.Player *-- java.awt.paint.Color
com.components.Player *-- java.awt.geom.AffineTransform

com.components.Spritesheet *-- com.components.Sprite

com.engine.LevelEditorScene *-- com.components.Grid
com.engine.LevelEditorScene *-- com.components.CameraControls
com.engine.LevelEditorScene *-- com.engine.GameObject
com.engine.LevelEditorScene *-- com.components.Spritesheet
com.engine.LevelEditorScene *-- com.components.Player
com.engine.LevelEditorScene *-- com.ui.MainContainer

com.engine.LevelScene *-- com.components.Spritesheet
com.engine.LevelScene *-- com.engine.GameObject
com.engine.LevelScene *-- com.components.Player

com.engine.Scene *-- com.engine.Camera
com.engine.Scene *-- java.util.ArrayList
com.engine.Scene *-- com.engine.Renderer

com.engine.Window *-- com.engine.MouseListener
com.engine.Window *-- com.engine.KeyListener
com.engine.Window *-- com.engine.LevelEditorScene
com.engine.Window *-- com.engine.LevelScene

com.ui.MainContainer *-- java.util.ArrayList
com.ui.MainContainer *-- com.components.Spritesheet
com.ui.MainContainer *-- com.engine.GameObject
com.ui.MainContainer *-- com.ui.MenuItem

com.util.AssetPool *-- java.io.File
com.util.AssetPool *-- com.components.Sprite
com.util.AssetPool *-- java.util.HashMap

com.util.Transform *-- com.util.Vector2D

@enduml